version: "3.8"
services:
  grails-app:
    build:
      context: .
    container_name: grails-container
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "8080:8080"
    command: [ "tail", "-f", "/dev/null" ]
    depends_on:
      - weatherdb
    networks:
      - grails_network

    weatherdb:
      image: mariadb:latest
      container_name: weatherdb
      restart: always
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      volumes:
        - mariadb_data:/var/lib/mysql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
        - grails_network

networks:
  grails_network:
volumes:
  mariadb_data: