info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
grails:
  cors:
    enabled: false
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      json:
        - application/json
        - text/json
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
      atom: application/atom+xml|
      css: text/css
      csv: text/csv
      js: text/javascript
      rss: application/rss+xml
      text: text/plain
      all: '*/*'
  views:
    default:
      codec: html
  codegen:
    defaultPackage: api.mobileApp
  profile: rest-api
dataSource:
  pooled: true
  jmxExport: true
  dialect: org.hibernate.dialect.MariaDBDialect
  driverClassName: org.mariadb.jdbc.Driver
  username: grails_user
  password: 'grails_password'
  properties:
    jmxEnabled: true
    initialSize: 5
    maxActive: 50
    minIdle: 5
    maxIdle: 25
    maxWait: 10000
    testOnBorrow: true
    testWhileIdle: true
    validationQuery: SELECT 1
    timeBetweenEvictionRunsMillis: 5000
environments:
  development:
    #    grails:
    #      mail:
    #        host: "smtp.gmail.com"
    #        port: 587
    #        username: ${SMTP_EMAIL}
    #        password: ${SMTP_EMAIL_PASSWORD}
    #        props:
    #          "mail.smtp.auth": "true"
    #          "mail.smtp.starttls.enable": "true"
    general:
      folder: /tmp/weather/
    dataSource:
      dbCreate: none
      url: jdbc:mariadb://weatherdb:3306/weather_app?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
  test:
    dataSource:
      dbCreate: update
      url: jdbc:h2:mem:testDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  production:
    dataSource:
      dbCreate: none
      url: jdbc:h2:./prodDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
gorm:
  default:
    failOnError: true
    autoFlush: true
  hibernate:
    dialect: org.hibernate.dialect.MariaDBDialect
  reactor:
    enabled: false
  multiTenancy:
    mode: DISCRIMINATOR
  mapping:
    scan:
      packages: [ 'api.mobileApp' ]
spring:
  h2:
    console:
      enabled: true
